server:
  port: 8080

spring:
  application:
    name: jobboard

  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: 2323
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always